apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  selector:
      matchlabels:
        app: tomcat
  replicas: 2	
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
	image: dockernikki/tomcat:latest
	ports:	 
        - containerPort: 8010
---

apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  ports:
  - protocol: TCP
    port: 8080
    targetport: 8080
    nodeport: 31000
  type: nodeport
